---
# tasks file for deb_k3s
- name: Update System Packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install requried Packages
  ansible.builtin.package:
    name: git
    state: latest

- name: Allow all access to tcp ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 6443

- name: Allow all access from internal networks
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
  loop:
    - 10.42.0.0/16
    - 10.43.0.0/16

- name: Check if K3s installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_result

- name: Install K3s
  shell: curl -sfL https://get.k3s.io | sh -
  when: not k3s_result.stat.exists
